// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:1073450813962:android:34243b3b2e96ce7f736df3',
    messagingSenderId: '1073450813962',
    projectId: 'generalapp-dev-3de9b',
    storageBucket: 'generalapp-dev-3de9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:1073450813962:ios:90520520e819d163736df3',
    messagingSenderId: '1073450813962',
    projectId: 'generalapp-dev-3de9b',
    storageBucket: 'generalapp-dev-3de9b.firebasestorage.app',
    iosClientId: '1073450813962-m4ohb5s0fai6of6571rad05bh0qh25tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gendralApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:1073450813962:web:5a66fe7b2be7a725736df3',
    messagingSenderId: '1073450813962',
    projectId: 'generalapp-dev-3de9b',
    authDomain: 'generalapp-dev-3de9b.firebaseapp.com',
    storageBucket: 'generalapp-dev-3de9b.firebasestorage.app',
    measurementId: 'G-LZHXCT31FY',
  );

}