// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2ts_e1SDsP4c4VHhFchV8t2dWXcp7JE',
    appId: '1:936056592369:web:425c1ddea0460004861650',
    messagingSenderId: '936056592369',
    projectId: 'genericapp-prod',
    authDomain: 'genericapp-prod.firebaseapp.com',
    storageBucket: 'genericapp-prod.firebasestorage.app',
    measurementId: 'G-HC53YDG4WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Fh0dAbxs8Lj_asG0Ui2aM937ZfshBhM',
    appId: '1:936056592369:android:6ec8d1e1e298fde6861650',
    messagingSenderId: '936056592369',
    projectId: 'genericapp-prod',
    storageBucket: 'genericapp-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXj884grWTR_esXYrBXTTO3EqNY0fc4nE',
    appId: '1:936056592369:ios:9eef809a9cd1b669861650',
    messagingSenderId: '936056592369',
    projectId: 'genericapp-prod',
    storageBucket: 'genericapp-prod.firebasestorage.app',
    iosClientId: '936056592369-7aau6ckpp7sf9t052cuubasusgglp12p.apps.googleusercontent.com',
    iosBundleId: 'com.snow.app',
  );

}