// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAX_CHFBmAqT4-NyJw0VFfs9Z8GYLJnY',
    appId: '1:25215427677:web:6d89faaf6ed1851e5c19b4',
    messagingSenderId: '25215427677',
    projectId: 'snow-appifybiz',
    authDomain: 'snow-appifybiz.firebaseapp.com',
    storageBucket: 'snow-appifybiz.firebasestorage.app',
    measurementId: 'G-Z6HHLVYTWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAFV6Qulh_x746-byURZfSZFvTKf2HFI',
    appId: '1:25215427677:android:2175a60a4e9a86c35c19b4',
    messagingSenderId: '25215427677',
    projectId: 'snow-appifybiz',
    storageBucket: 'snow-appifybiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEMK833XuDhcswSzuyLZbSTT-S7QHpi8',
    appId: '1:25215427677:ios:60095104ce4e6c485c19b4',
    messagingSenderId: '25215427677',
    projectId: 'snow-appifybiz',
    storageBucket: 'snow-appifybiz.firebasestorage.app',
    iosBundleId: 'com.snow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAX_CHFBmAqT4-NyJw0VFfs9Z8GYLJnY',
    appId: '1:25215427677:web:d3e41dc761b6f27d5c19b4',
    messagingSenderId: '25215427677',
    projectId: 'snow-appifybiz',
    authDomain: 'snow-appifybiz.firebaseapp.com',
    storageBucket: 'snow-appifybiz.firebasestorage.app',
    measurementId: 'G-ZGHEDZ5GMX',
  );
}
